server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/cms?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 100
      thread-name-prefix: bulk-upload-
  mvc:
    async:
      request-timeout: 300000
